//
//  Resolver.swift
//  Generated by dikitgen.
//

import DIKit
import Foundation
import RxCocoa
import RxDataSources
import RxSwift
import SVProgressHUD
import SafariServices
import UIKit

extension AppResolver {

    func injectToHomeViewController(_ homeViewController: HomeViewController) -> Void {
        let homeViewModel = resolveHomeViewModel()
        homeViewController.dependency = HomeViewController.Dependency(homeViewModel: homeViewModel)
    }

    func resolveAppResolver() -> AppResolver {
        return provideResolver()
    }

    func resolveHomeConvertSentenseUsecaseProtocol() -> HomeConvertSentenseUsecaseProtocol {
        return provideHomeConvertUsecase()
    }

    func resolveHomeViewModel() -> HomeViewModel {
        return provideHomeViewModel()
    }

}

